# Run this file to start the server

from flask import Flask
from flask_cors import CORS

def create_app():
    """
    This function creates the Flask app, which is the main server to handle the autofill requests

    Returns:
    app (Flask): The Flask app
    """
    app = Flask(__name__)
    app.config['SECRET_KEY'] = '0f5945a3ad64f820eae65124' # generated by os.urandom
    CORS(app)
    from routes import main
    app.register_blueprint(main)
    return app

if __name__ == '__main__':
    app = create_app()
    app.run(debug=True)
